src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/templates/_brandname.html
NCTime!!

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">When stomach gives you too much lime, It's NCTIME!! :D</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/kar1.jpg' %}" alt="profile pic" height="200" width="200"></div>
        <p class="heavy text-center">Akankshya Kar</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/deeps.jpg' %}"alt="profile pic" height="200" width="200"></div>
        <p class="heavy text-center">Deepti Rajagopal</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" height="200" width="200" src="{% static 'site/img/prash.jpg' %}" alt="profile pic"></div>
        <p class="heavy text-center">Prashasthi Mavin</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/style.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <!--<div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>NC order online.</p>
	  
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>-->
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

	<div id="page">
		<div id="header">
			<div id="sidebar">
				<a href="index.php" id="logo"><img src="{% static 'site/img/logo2.png' %}" height="182" width="220" alt="LOGO"></a>
				<div id="navigation">
					<ul>
						<li class="selected">
							<a href="index.php">Home</a>
						</li>
						<li class="menu">
							<a href="index.php">Menu</a>
							<div class="sub">
								<a href="menug.php">GB NC</a> <a href="menutr.php">TRUPTI NC</a> <a href="menupr.php">Prasanth NC</a> <a href="menu3rd.php" class="last-child">3rd Block NC</a>
							</div>
							<span></span>
						</li>
						<li>
							<a href="login.php">LOGIN for NC</a>
						</li>
						<li class="last1">
							<a href="comp.php">Read Reviews</a>
						</li>
						<li class="last">
							<a href="complaint.php">Write Reviews</a>
						</li>
					</ul>
				</div>
			</div>
			<div id="adbox">
				<h1>NITK CANTEENS!!!</h1>
				<div class="frame">
					<div class="section">
						<p>


							This is the ultimate website to order food for us,NITKians. All NC's one place!! This website gives you the best deal all the time. Order anytime... and from any NC in campus...
						</p>
					</div>
					<div class="section">
						<h2>Order from ANY NC, ANY time  and get the BEST deals!!</h2>
					</div>
				</div>
			</div>
		</div>
		<div id="contents">
			<div id="articles">
				<div>
					<div class="frame">
						<img src="{% static 'site/img/chickenkebab.jpeg' %}" alt="Img" height="180" width="180">
						<h2>Chicken Kebab</h2>
						<p>
							Heaven for non-vegetarians!! Amazing prices and even better quality of chicken items. Compare through NCs and choose the one you like the most. Prashant and GB NC give best quality chicken in affordale prices. 
						</p>
						<!--<a href="index.php" class="more">put comapare thing now</a>-->
					</div>
					<div class="frame">
						<img src="{% static 'site/img/dosa.jpeg' %}" alt="Img" height="192" width="189">
						<h2>DOSA!!</h2>
						<p>
							Yummy Dosas in every NC!! Ranging from sada dosa to schezwan Dosa..All at unbelievable prices. Click this link to compare the dosas. Because HUNGRY KYA??? DOSA kha :P
						</p>
						<a href="index.php" class="more">Learn More</a>
					</div>
					<div id="featured">
						<ul>
							<li>
								<a href="menug.php"> <img src="{% static 'site/img/GBNC.png' %}" height="170" width="180" alt="Img">
							    <h3>GB NC</h3>
								</a>
							</li>
							<li>
								<a href="menutr.php"> <img src="{% static 'site/img/trupti.jpeg' %}" height="170" width="180" alt="Img">
								<h3>TRUPTI NC</h3>
								</a>
							</li>
							<li>
								<a href="menupr.php"> <img src="{% static 'site/img/prasanth.jpeg' %}" height="170" width="180" alt="Img">
								<h3>PRASANTH NC</h3>
								</a>
							</li>
							<li>
								<a href="menu3rd.php"> <img src="{% static 'site/img/3block.png' %}" height="170" width="180" alt="Img">
								<h3>3rd BLOCK NC</h3>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div id="dummy">
			</div>
		</div>
		<div id="footer">
			<div class="header">
				<div class="body">
					<ul>
						<li>
							<h4>Reach non-veg NCs</h4>
							<span>&gt; <a href="menug.php">GB NC</a></span> <span>&gt; <a href="menupr.php"> Prasanth NC</a></span>
						</li>
						<li>
							<h4>Dosa</h4>
							<span>&gt; <a href="#header">plain</a></span> <span>&gt; <a href="#header"> MASALA</a></span> <span>&gt; <a href="#header">Cheese</a></span>
						</li>
						<li>
							<h4>PARATHA</h4>
							<span>&gt; <a href="#header">ALOO</a></span> <span>&gt; <a href="#header">PANEER</a></span> <span>&gt; <a href="#header">chandini chowk</a></span>
						</li>
						<li class="last-child">
							<h4>NC LOGIN</h4>
							<span>&gt; <a href="#header">Create Account</a></span> <span>&gt; <a href="login.php">Manage Account</a></span> <span>&gt; <a href="#header">Get Upgrade</a></span>
						</li>
					</ul>
				</div>
				<div class="footer">
					
					<p>
						Copyright 2015 Company Name. All Rights Reserved.
					</p>
				</div>
			</div>
			<p id="footnote">
				This website has been designed by Akankshya, Debarati and Deepti.Its for the sole purpose of DBMS project. And rights are reserved. Intellectual property is reserved.
			</p>
		</div>
	</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}